---
title: "analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
data <- read_excel("NIH P1 Emotion Understanding SDS300.xlsx")

data <- janitor::clean_names(data, 'snake')
```


Univariate Analysis:
```{r}
#males vs females in the study
ggplot(data, aes(x = gender_1)) +
  geom_histogram()

summary(data$gender_1)

#distribution of word spans according to gender
ggplot(data, aes(x = word_span)) +
  geom_histogram() +
  facet_grid(vars(gender))

summary(data$word_span)

#age distribution for males vs females
ggplot(data, aes(x = age_1)) +
  geom_histogram() +
  facet_grid(vars(gender))

summary(data$age_1)

#PLS4 score distribution male vs female
ggplot(data, aes(x = pls4comp_raw1)) +
  geom_histogram() +
  facet_grid(vars(gender))

summary(data$pls4comp_raw1)
summary(data$pls4_comp_raw3)
#increase from 1 to 3

#EOWPVT raw score distribution male vs female 
ggplot(data, aes(x = eowpvt_raw1)) +
  geom_histogram() +
  facet_grid(vars(gender))

summary(data$eowpvt_raw1)
summary(data$eowpvt_raw3)
#increase from 1 to 3

#EMO sit 1 distrubution
ggplot(data, aes(x = emo_sit_1)) +
  geom_histogram() +
  facet_grid(vars(gender))

summary(data$emo_sit_1)
summary(data$emo_sit_3)
#only slight inc

#look at total pre emotional score for intervention groups vs no intervention
ggplot(data, aes(x = emo_total_1)) +
  geom_histogram() +
  facet_grid(vars(intervention))

summary((data %>% filter(intervention == 1))$emo_total_1)
summary((data %>% filter(intervention == 0))$emo_total_1)
#both groups start off pretty similar

#look at total post emotional score for intervention groups vs no intervention
ggplot(data, aes(x = emo_total_3)) +
  geom_histogram() +
  facet_grid(vars(intervention))

summary((data %>% filter(intervention == 1))$emo_total_3)
summary((data %>% filter(intervention == 0))$emo_total_3)

#compare emo_total_1 to emo_total_3; did intervention make a difference?
```

Bivariate Analysis
```{r}
#word span vs total emotional score
ggplot(data, aes(x = word_span, y = emo_total_1)) +
  geom_point() +
  geom_jitter()

ggplot(data, aes(x = word_span, y = emo_total_3)) +
  geom_point() +
  geom_jitter()

#it looks like there is a more linear relationship for 3 than 1




#scatterplot between word span and emotion score - do kids with a higher word span have better emotional understanding? 
ggplot(data, aes(x = word_span, y = emo_total_3, color = gender)) +
  geom_point() +
  geom_jitter()
```


try different linear regression models
```{r}
mod1 <- lm(emo_total_3 ~ word_span, data = data %>% filter(intervention == 1))
summary(mod1)
#very weak R and R^2, but filtering for intervention improves it


mod2 <- lm(word_span ~ pls4comp_raw1, data = data)
summary(mod2)

mod3 <- lm(word_span ~ pls4_comp_raw3, data = data)
summary(mod3)
#stronger using post scores vs pre scores

mod4 <- lm(word_span ~ pls4_comp_raw3, data = data %>% filter(intervention == 1))
summary(mod4)
#similar strength to control group

mod5 <- lm(emo_total_3 ~ word_span + eowpvt_raw3, data = data %>% filter(intervention == 0))
summary(mod5)
#basically no linear correlation at all for control group
  
mod6 <- lm(emo_total_3 ~ word_span + eowpvt_raw3 + pls4_comp_raw3, data = data %>% filter(intervention == 1))
summary(mod6)
#more linear correlation for intervention group!



#filter for explicit emotion group
mod7 <- lm(emo_total_3 ~ word_span + eowpvt_raw3 + pls4_comp_raw3, data = data %>% filter(i_group == 2))
summary(mod7)
#explicit emotion group has a much more linear correlation!!! r is close to 0.5, highest so far

#filter for implicit emotion group
mod8 <- lm(emo_total_3 ~ word_span + eowpvt_raw3 + pls4_comp_raw3, data = data %>% filter(i_group == 3))
summary(mod8)
#weaker correlation 

#filter for control group
mod9 <- lm(emo_total_3 ~ word_span + eowpvt_raw3 + pls4_comp_raw3, data = data %>% filter(i_group == 1))
summary(mod9)
#basically no linear correlation 


#relationship between pre and post emo scores for each:

#filter for control group
mod10 <- lm(emo_total_3 ~ i_group, data = data)
summary(mod10)
#r^2 is basically zero
  

```

